cursor #31363b

foreground            #31363b
background            #fcfcfc

# black
color0 #232627
color8 #7f8c8d

# red
color1 #c0392b
color9 #ed1515

# green
color2  #1a9c2d
color10 #2ecc71

# yellow
color3  #c47517
color11 #f67400

# blue
color4  #1b6fb3
color12 #1d99f3

# magenta
color5  #7b3d9e
color13 #9b59b6

# cyan
color6  #148f7b
color14 #1abc9c

# white
color7  #e8e8e8
color15 #fcfcfc
