# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:/home/breengles/.local/bin:$PATH

source /Users/breengles/antigen.zsh

# Oh-my-zsh
antigen use oh-my-zsh

# Bundles
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle esc/conda-zsh-completion

# Theme
antigen theme robbyrussell

# We are done
antigen apply

# Intel's OneAPI
. /opt/intel/oneapi/setvars.sh >/dev/null

# Example aliases
alias zshconfig="vim ~/.zshrc"
# alias ohmyzsh="vim ~/.oh-my-zsh"

alias c="clear"
alias sizeof="du -shc"

alias py="python3"
alias pip="pip3"
alias ipy="ipython3"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/breengles/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/breengles/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/breengles/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/breengles/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

