/**
 * web_search -- active-model summary
 *
 * Replaces pi-web-access's `web_search` with a leaner flow that reuses its
 * search pipeline verbatim, then generates the summary with the *currently
 * active* model instead of the static `summaryModel` from ~/.pi/web-search.json.
 *
 * Why this works without patching pi-web-access: `generateSummaryDraft` takes a
 * `modelOverride` ("provider/id") and resolves candidates as
 * `[modelOverride, ...PREFERRED_SUMMARY_MODELS]`, so passing the active model
 * here keeps the existing preferred-default + deterministic fallback chain.
 *
 * pi-web-access's own `web_search` must be disabled so this tool can claim the
 * name; see .pi/web-search.json:
 *
 *   { "tools": { "webSearch": { "enabled": false } } }
 */

import { homedir } from "node:os";
import { join } from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

// pi-web-access ships no `exports` map and is a separate pi package (separate
// module root), so import its building blocks by absolute path. Resolve
// dynamically so reinstalls and `PI_CODING_AGENT_DIR` overrides keep working.
const PACKAGE_DIR = join(
	process.env.PI_CODING_AGENT_DIR ?? join(homedir(), ".pi", "agent"),
	"npm",
	"node_modules",
	"pi-web-access",
);

type SearchResultItem = { title: string; url: string; snippet: string };

type SearchProviderResponse = {
	answer: string;
	results: SearchResultItem[];
	provider: string;
};

type SearchResponse = SearchProviderResponse & {
	providerResponses?: SearchProviderResponse[];
	providerErrors?: Array<{ provider: string; error: string }>;
};

type SearchOptions = {
	provider?: string | string[];
	numResults?: number;
	recencyFilter?: "day" | "week" | "month" | "year";
	domainFilter?: string[];
	signal?: AbortSignal;
	extensionContext?: unknown;
};

type QueryResult = {
	query: string;
	answer: string;
	results: SearchResultItem[];
	error: string | null;
	provider?: string;
};

type SummaryMeta = {
	model: string | null;
	fallbackUsed: boolean;
	durationMs: number;
	tokenEstimate: number;
	fallbackReason?: string;
	phase?: string;
};

type Blocks = {
	search: (query: string, options?: SearchOptions) => Promise<SearchResponse>;
	generateSummaryDraft: (
		results: QueryResult[],
		ctx: Record<string, unknown>,
		signal?: AbortSignal,
		modelOverride?: string,
		feedback?: string,
		completeFn?: unknown,
		deadlineMs?: number,
	) => Promise<{ summary: string; meta: SummaryMeta }>;
};

let blocksPromise: Promise<Blocks> | null = null;

function loadBlocks(): Promise<Blocks> {
	if (!blocksPromise) {
		blocksPromise = Promise.all([
			import(join(PACKAGE_DIR, "gemini-search.ts")),
			import(join(PACKAGE_DIR, "summary-review.ts")),
		]).then(([searchMod, summaryMod]) => ({
			search: searchMod.search as Blocks["search"],
			generateSummaryDraft: summaryMod.generateSummaryDraft as Blocks["generateSummaryDraft"],
		}));
	}
	return blocksPromise;
}

function isAbortError(err: unknown): boolean {
	return (err instanceof Error ? err.message : String(err)).toLowerCase().includes("abort");
}

/** Split an AttributedSearchResponse into per-provider query results. */
function toQueryResults(query: string, response: SearchResponse): QueryResult[] {
	const responses =
		response.provider === "all" && response.providerResponses?.length
			? response.providerResponses
			: [response];
	const results: QueryResult[] = responses.map((r) => ({
		query,
		answer: r.answer,
		results: r.results,
		error: null,
		provider: r.provider,
	}));
	for (const failure of response.providerErrors ?? []) {
		results.push({ query, answer: "", results: [], error: failure.error, provider: failure.provider });
	}
	return results;
}

function formatSources(results: QueryResult[]): string {
	const lines: string[] = [];
	let i = 0;
	for (const r of results) {
		for (const s of r.results) {
			i += 1;
			lines.push(`${i}. ${s.title}\n   ${s.url}`);
		}
	}
	return lines.join("\n\n");
}

export default function (pi: ExtensionAPI) {
	pi.registerTool({
		name: "web_search",
		label: "Web Search",
		description:
			"Search the web through the configured pi-web-access provider chain (SearXNG, OpenAI, Exa, Brave, and more, with automatic fallback) and return a summary generated by the currently active model. Supports a single query or a batch of queries; prefer multiple varied queries for broader coverage. Omit provider to use the configured default, or pass a provider name or array of providers. There is no browser curator; results are summarized directly.",
		promptSnippet:
			"Use for web research. Prefer {queries:[...]} with 2-4 varied angles over a single query for broader coverage. Omit provider unless overriding the configured default.",
		parameters: Type.Object({
			query: Type.Optional(Type.String({ description: "Single search query" })),
			queries: Type.Optional(Type.Array(Type.String(), { description: "Multiple queries searched in sequence" })),
			numResults: Type.Optional(Type.Integer({ minimum: 1, maximum: 20, description: "Results per query (default: 5)" })),
			recencyFilter: Type.Optional(
				Type.Union(
					[Type.Literal("day"), Type.Literal("week"), Type.Literal("month"), Type.Literal("year")],
					{ description: "Filter by recency" },
				),
			),
			domainFilter: Type.Optional(Type.Array(Type.String(), { description: "Limit to domains (prefix with - to exclude)" })),
			provider: Type.Optional(
				Type.Union([Type.String(), Type.Array(Type.String())], {
					description: "Search provider or list of providers; omit to use the configured default",
				}),
			),
		}),
		async execute(_callId, params, signal, _onUpdate, ctx) {
			if (!ctx || !ctx.modelRegistry) {
				return {
					content: [{ type: "text", text: "Error: no extension context available." }],
					details: { error: "Missing extension context" },
				};
			}

			const rawQueries: unknown[] = Array.isArray(params.queries)
				? params.queries
				: (params.query !== undefined ? [params.query] : []);
			const queries = rawQueries
				.filter((q): q is string => typeof q === "string" && q.trim().length > 0)
				.map((q) => q.trim());
			if (queries.length === 0) {
				return {
					content: [{ type: "text", text: "Error: no query provided. Use 'query' or 'queries'." }],
					details: { error: "No query provided" },
				};
			}

			let blocks: Blocks;
			try {
				blocks = await loadBlocks();
			} catch (err) {
				const message = err instanceof Error ? err.message : String(err);
				return {
					content: [{ type: "text", text: `Error: pi-web-access could not be loaded (${PACKAGE_DIR}): ${message}` }],
					details: { error: message },
				};
			}

			const results: QueryResult[] = [];
			const urls: string[] = [];
			for (const query of queries) {
				try {
					const response = await blocks.search(query, {
						provider: params.provider,
						numResults: params.numResults,
						recencyFilter: params.recencyFilter,
						domainFilter: params.domainFilter,
						signal,
						extensionContext: ctx,
					});
					for (const r of toQueryResults(query, response)) {
						results.push(r);
						for (const s of r.results) if (!urls.includes(s.url)) urls.push(s.url);
					}
				} catch (err) {
					if (signal?.aborted || isAbortError(err)) throw err;
					const message = err instanceof Error ? err.message : String(err);
					results.push({
						query,
						answer: "",
						results: [],
						error: message,
						provider: typeof params.provider === "string" ? params.provider : undefined,
					});
				}
			}

			const summaryContext = {
				model: ctx.model,
				modelRegistry: ctx.modelRegistry,
				cwd: ctx.cwd,
				isProjectTrusted: () => ctx.isProjectTrusted(),
			};
			const activeModel = ctx.model ? `${ctx.model.provider}/${ctx.model.id}` : undefined;
			const { summary, meta } = await blocks.generateSummaryDraft(results, summaryContext, signal, activeModel);

			const sources = formatSources(results);
			const text = sources ? `${summary}\n\n---\n\n**Sources:**\n${sources}` : summary;

			return {
				content: [{ type: "text", text }],
				details: {
					queries,
					queryCount: queries.length,
					totalResults: results.reduce((n, r) => n + r.results.length, 0),
					urls,
					summaryModel: meta.model,
					summaryFallbackUsed: meta.fallbackUsed,
					summaryFallbackReason: meta.fallbackReason,
					summaryDurationMs: meta.durationMs,
					summaryTokenEstimate: meta.tokenEstimate,
					summaryPhase: meta.phase,
				},
			};
		},
	});
}
